spring:
  application:
    name: course-app
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/university
  jpa:
    show-sql: true
    properties:
       hibernate:
       format_sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
      

logging:
  level:  
   org:
    hibernate:
     SQL: DEBUG
     type:
      descriptor:
      sql:
       BasicBinder: TRACE